apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: helep-kafka-broker-pdb
  namespace: kafka
spec:
  minAvailable: 1
  selector:
    matchLabels:
      strimzi.io/cluster: helep-kafka
      strimzi.io/name: helep-kafka-kafka
